apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zuul-api-gateway"
  labels:
    app: "zuul-api-gateway"
spec:
  selector:
    matchLabels:
      app: "zuul-api-gateway"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "zuul-api-gateway"
    spec:
      containers:
      - name: "zuul-api-gateway"
        image: manjeetyadav19/zuul:latest
        ports:
        - containerPort: 9999 
          name: "zuul-api"
---

apiVersion: v1
kind: Service
metadata:
  name: "zuul-api-gateway"
spec:
  selector:
    app: "zuul-api-gateway"
  type: NodePort
  ports:
  - port: 9999
    targetPort: 9999

