apiVersion: apps/v1
kind: Deployment
metadata:
  name: "shoe"
  labels:
    app: "shoe"
spec:
  selector:
    matchLabels:
      app: "shoe"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "shoe"
    spec:
      containers:
      - name: "shoe"
        image: manjeetyadav19/shoe:latest
        ports:
        - containerPort: 1002
          name: "shoe"
---

apiVersion: v1
kind: Service
metadata:
  name: "shoe"
spec:
  selector:
    app: "shoe"
  type: ClusterIP
  ports:
  - port: 1002
    targetPort: 1002

