apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cart"
  labels:
    app: "cart"
spec:
  selector:
    matchLabels:
      app: "cart"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "cart"
    spec:
      containers:
      - name: "cart"
        image: manjeetyadav19/cart:latest
        ports:
        - containerPort: 1004
          name: "cart"
---

apiVersion: v1
kind: Service
metadata:
  name: "cart"
spec:
  selector:
    app: "cart"
  type: ClusterIP
  ports:
  - port: 1004
    targetPort: 1004

