apiVersion: apps/v1
kind: Deployment
metadata:
  name: "discovery"
  labels:
    app: "discovery"
spec:
  selector:
    matchLabels:
      app: "discovery"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "discovery"
    spec:
      containers:
      - name: "discovery"
        image: manjeetyadav19/discovery:latest
        ports:
        - containerPort: 8761
          name: "discovery"
---

apiVersion: v1
kind: Service
metadata:
  name: "discovery"
spec:
  selector:
    app: "discovery"
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761

